version: '3.8'
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_port: 5432
      postgres_user: admin
      postgres_pass: admin123
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mumbai:https://polygon-mumbai.g.alchemy.com/v2/THNAV_YQRlVGVAVI9lq5Q0tl0T88rMi9'
      RUST_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    # volumes:
    #   - /data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: graph-node
    # volumes:
    #   - /data/postgres:/data/postgres