# Ref: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-github-packages
name: Deployment to dev
on:
  push:
    branches:
      - dev
    paths:
      - packages/seacows-amm/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@master

      - name: seacows-bot-install token
        id: seacows-bot
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.SEACOWS_BOT_APP_ID }}
          private_key: ${{ secrets.SEACOWS_BOT_PRIVATE_KEY }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@yolominds"

      - name: Deploy Goerli
        run: |
          yarn workspace @yolominds/seacows-amm install
          yarn workspace @yolominds/seacows-amm run prepare:dev:goerli
          yarn workspace @yolominds/seacows-amm run build
          yarn workspace @yolominds/seacows-amm run deploy:dev:goerli

      # BELOW are for docker deployment
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      #     aws-region: ap-southeast-1

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: "[Goerli] Build, tag, and push image to Amazon ECR"
      #   env:
      #     ECR_REGISTRY: 740358724789.dkr.ecr.ap-southeast-1.amazonaws.com
      #     ECR_REPOSITORY: graph-node-deployer-goerli-dev
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg NPM_TOKEN=${{ secrets.NPM_AUTH_TOKEN }}
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # # Reserve for Mumbai
      # # - name: "[Mumbai] Build, tag, and push image to Amazon ECR"
      # #   env:
      # #     ECR_REGISTRY: 740358724789.dkr.ecr.ap-southeast-1.amazonaws.com
      # #     ECR_REPOSITORY: seacows-backend-dev
      # #     IMAGE_TAG: ${{ github.sha }}
      # #   run: |
      # #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg github_token=${{ secrets.READ_WRITE_GITHUB_PACKAGES_SECRET }}
      # #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # # Update kubeconfig for deployment
      # - uses: actions/checkout@master
      #   with:
      #     repository: yolominds/ops-kubeconfig
      #     # ref: refs/heads/master
      #     token: ${{ steps.seacows-bot.outputs.token }}

      # - name: Setup Kustomize
      #   uses: imranismail/setup-kustomize@v1
      #   with:
      #     kustomize-version: "3.6.1"
      # - name: "[Goerli] Run kustomize"
      #   env:
      #     IMAGE_NAME: graph-node-deployer
      #     NEW_IMAGE_NAME: 740358724789.dkr.ecr.ap-southeast-1.amazonaws.com/graph-node-deployer-goerli-dev
      #     NEW_IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     cd services/graph-node/overlays/dev/goerli
      #     kustomize edit set image $IMAGE_NAME=$NEW_IMAGE_NAME:$NEW_IMAGE_TAG

      # # - name: "[Mumbai] Run kustomize"
      # #   env:
      # #     IMAGE_NAME: graph-node-deployer
      # #     NEW_IMAGE_NAME: 740358724789.dkr.ecr.ap-southeast-1.amazonaws.com/graph-node-deployer-dev-goerli
      # #     NEW_IMAGE_TAG: ${{ github.sha }}
      # #   run: |
      # #     cd services/graph-node-deployer/overlays/dev/goerli
      # #     kustomize edit set image $IMAGE_NAME=$NEW_IMAGE_NAME:$NEW_IMAGE_TAG

      # - name: Git config
      #   run: |
      #     git config --local user.email "tech@seacows.io"
      #     git config --local user.name "Seacows Bot"
      #     git commit -am "chore(release-dev): deploy graph-node-deployer to dev"

      # - name: Push updated version to master
      #   uses: ad-m/github-push-action@master
      #   with:
      #     repository: yolominds/ops-kubeconfig
      #     branch: main
      #     tags: true
      #     github_token: ${{ steps.seacows-bot.outputs.token }}

